package(default_visibility = ["//visibility:public"])

exports_files(glob(["*"]))

filegroup(
    name = "all",
    srcs = [
        "ar",
        "clang",
        "cpp",
        "ld",
        "nm",
        "objcopy",
        "objdump",
        "strip",
    ],
)
